<nav class="breadcrumb">
    <i class="Hui-iconfont">&#xe67f;</i> 首页
    <span class="c-gray en">&gt;</span> 用户管理
    <span class="c-gray en">&gt;</span> 用户
</nav>

<div class="page-container">
    <div class="cl pd-5 bg-1 bk-gray mt-20">
        <span class="l">
            <a href="javascript:;" onclick="user_group(2, '');" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe676;</i> 批量选择分组</a>
            <a href="javascript:;" onclick="import_group();" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe645;</i> 批量导入分组</a>
        </span> <span class="r">共有数据：<strong><?php echo isset($total) ? $total : 0;?></strong> 条</span> </div>
    <div class="mt-20">
        <table class="table table-border table-bordered table-hover table-bg table-sort">
            <thead>
            <tr class="text-c">
                <th width="25"><input type="checkbox" name="" value=""></th>
                <th width="50">头像</th>
                <th width="60">昵称</th>
                <th width="60">用户组</th>
                <th width="120">openid</th>
                <th width="60">操作</th>
            </tr>
            </thead>
            <tbody>
            <?php if (isset($result) && $result && $result->user_info_list) {?>
            <?php foreach($result->user_info_list as $user) {?>
                <tr class="text-c">
                    <td><input type="checkbox" value="<?php echo $user['openid'];?>" name="user-checkbox"></td>
                    <td><img style="width:50px;height:50px;" src="<?php echo $user['headimgurl'];?>" /></td>
                    <td><?php echo $user['nickname'];?></td>
                    <td><?php echo isset($groups[$user['groupid']]) ? $groups[$user['groupid']] : '';?></td>
                    <td><?php echo $user['openid'];?></td>
                    <td class="td-manage">
                        <a href="javascript:;" onclick="user_group(1, '<?php echo $user['openid'];?>');" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe62b;</i> 分组</a>
                    </td>
                </tr>
            <?php }} else {?>
                <tr class="text-c">
                    <td colspan="6">还没有用户</td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<div id="pop-select-group" class="hide">
    <form action="" method="post" class="form form-horizontal">
        <div class="cl" style="margin-top: 20px;">
            <label class="form-label col-xs-4 col-sm-5">选择分组：</label>
            <div class="formControls col-xs-8 col-sm-6">
                <?php if (isset($groups) && $groups) {?>
                <span class="select-box">
                    <select class="select" size="1" name="group" id="group">
                        <?php foreach ($groups as $groupid => $groupname) {?>
                            <option value="<?php echo $groupid;?>"><?php echo $groupname;?></option>
                        <?php } ?>
                    </select>
                </span>
                <?php } ?>
            </div>
        </div>
        <div class="cl" style="margin-top: 20px;">
            <div class="" style="text-align: center;">
                <input type="hidden" id="openid" value="" />
                <input class="btn btn-default radius" type="button" id="btn-cancel" value="&nbsp;&nbsp;取消&nbsp;&nbsp;">&nbsp;&nbsp;&nbsp;&nbsp;
                <input class="btn btn-primary radius" type="button" id="btn-ok" value="&nbsp;&nbsp;确认&nbsp;&nbsp;">
            </div>
        </div>
    </form>
</div>

<!-- 批量导入分组 -->
<div id="pop-import-group" class="hide">
    <form action="" method="post" class="form form-horizontal">
        <div class="cl" style="margin-top: 20px;">
            <label class="form-label col-xs-4 col-sm-3">选择分组：</label>
            <div class="formControls col-xs-8 col-sm-7">
                <?php if (isset($groups) && $groups) {?>
                    <span class="select-box">
                    <select class="select" size="1" name="import-group" id="import-group">
                        <?php foreach ($groups as $groupid => $groupname) {?>
                            <option value="<?php echo $groupid;?>"><?php echo $groupname;?></option>
                        <?php } ?>
                    </select>
                </span>
                <?php } ?>
            </div>
        </div>
        <div class="cl" style="margin-top: 20px;">
            <label class="form-label col-xs-4 col-sm-3">openid：</label>
            <div class="formControls col-xs-8 col-sm-7">
                <textarea name="openids" id="openids" cols="" rows="" class="textarea"  placeholder=""></textarea>
                <p style="font-size: 0.8em;">(多个openid以逗号 "," 隔开)</p>
            </div>
        </div>
        <div class="cl" style="margin-top: 20px;">
            <div class="" style="text-align: center;">
                <input class="btn btn-default radius" type="button" id="btn-import-cancel" value="&nbsp;&nbsp;取消&nbsp;&nbsp;">&nbsp;&nbsp;&nbsp;&nbsp;
                <input class="btn btn-primary radius" type="button" id="btn-import-ok" value="&nbsp;&nbsp;确认&nbsp;&nbsp;">
            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="/h-ui.admin/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
/*批量导入分组*/
function import_group() {
    layer.open({
        type: 1,
        shade: false,
        title: '批量导入用户分组', // 标题
        area: ['640px', '320px'],
        closeBtn: 0, // 不显示关闭按钮
        content: $('#pop-import-group')
    });
}

/*用户分组*/
function user_group(type, openid) {
    if (type == 2) { // 批量分组
        var openid = '';
        $("input[name='user-checkbox']:checked").each(function(){
            openid += $(this).val() + ',';
        })
        if (openid) {
            openid = openid.substring(0, openid.length - 1);
        }
    }
    if (openid) {
        $("input#openid").val(openid);
        layer.open({
            type: 1,
            shade: false,
            title: '用户分组', // 标题
            area: ['320px', '180px'],
            closeBtn: 0, // 不显示关闭按钮
            content: $('#pop-select-group')
        });
    } else {
        layer.alert("请选择用户！");
    }
}
$(function() {
    $("#btn-cancel").click(function () {
        $("input#openid").val('');
        layer.closeAll();
    });
    $("#btn-ok").click(function() {
        var openid = $("input#openid").val();
        var groupid = $("select#group").val();
        $.post('/user/user_to_group', {groupid: groupid, openid: openid}, function(data) {
            if (data.errcode == 0) {
                window.location.reload();
            } else {
                layer.msg(data.msg);
            }
        });
    });

    $("#btn-import-cancel").click(function () {
        layer.closeAll();
    });
    $("#btn-import-ok").click(function() {
        var openid = $.trim($("textarea#openids").val());
        var groupid = $("select#import-group").val();
        if (openid) {
            $.post('/user/user_to_group', {groupid: groupid, openid: openid}, function (data) {
                if (data.errcode == 0) {
                    window.location.reload();
                } else {
                    layer.msg(data.msg);
                }
            });
        } else {
            layer.msg('请输入openid');
            $("textarea#openids").focus();
        }
    });
});
</script>