<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/h-ui.admin/lib/html5.js"></script>
    <script type="text/javascript" src="/h-ui.admin/lib/respond.min.js"></script>
    <script type="text/javascript" src="/h-ui.admin/lib/PIE_IE678.js"></script>
    <![endif]-->
    <link href="/h-ui.admin/static/h-ui/css/H-ui.min.css" rel="stylesheet" type="text/css" />
    <link href="/h-ui.admin/static/h-ui.admin/css/H-ui.login.css" rel="stylesheet" type="text/css" />
    <link href="/h-ui.admin/static/h-ui.admin/css/style.css" rel="stylesheet" type="text/css" />
    <link href="/h-ui.admin/lib/Hui-iconfont/1.0.7/iconfont.css" rel="stylesheet" type="text/css" />
    <!--[if IE 6]>
    <script type="text/javascript" src="/js/DD_belatedPNG_0.0.8a-min.js" ></script>
    <script>DD_belatedPNG.fix('*');</script>
    <![endif]-->
    <title>登录 - 微信公众平台管理系统</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
</head>
<body>
<input type="hidden" id="TenantId" name="TenantId" value="" />
<!--<div class="header"></div>-->
<div class="loginWraper">
    <div id="loginform" class="loginBox">
        <form class="form form-horizontal" action="" method="post">
            <div class="row cl">&nbsp;</div>
            <div class="row cl">
                <label class="form-label col-xs-3"><i class="Hui-iconfont">&#xe60d;</i></label>
                <div class="formControls col-xs-8">
                    <input id="username" name="username" type="text" placeholder="账 户" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-3"><i class="Hui-iconfont">&#xe60e;</i></label>
                <div class="formControls col-xs-8">
                    <input id="password" name="password" type="password" placeholder="密码" class="input-text size-L">
                </div>
            </div>

            <div class="row cl">
                <div class="formControls col-xs-8 col-xs-offset-3">
                    <label for="online">
                        <input type="checkbox" name="remember_me" id="remember_me" value="">
                        记住密码
                    </label>
                </div>
            </div>
            <div class="row cl">
                <div class="formControls col-xs-8 col-xs-offset-3">
                    <input name="submit" type="button" id="btn-submit" class="btn btn-success radius size-L" value="&nbsp;登&nbsp;&nbsp;&nbsp;&nbsp;录&nbsp;">
                </div>
            </div>
        </form>
    </div>
</div>
<!--<div class="footer">Copyright &copy; 2016 碰碰坑</div>-->
<script type="text/javascript" src="/h-ui.admin/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/h-ui.admin/static/h-ui/js/H-ui.js"></script>
<script type="text/javascript">
$(function () {
    $("#btn-submit").click(function() {
        var username = $.trim($("#username").val());
        var password = $.trim($("#password").val());
        var remember_me = $("#remember_me").val();
        if (username == '') {
            alert('请输入账号！')
            return false;
        }
        if (password == '') {
            alert('请输入密码！');
            return false;
        }
        $.post('/signin', {username: username, password: password, remember_me: remember_me}, function(data) {
            if (data.errcode == 0) {
                window.location.href = "/";
            } else {
                alert(data.msg);
            }
        });
    });
});
</script>
</body>
</html>