<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <LINK rel="Bookmark" href="/favicon.ico" >
    <LINK rel="Shortcut Icon" href="/favicon.ico" />
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/h-ui.admin/lib/html5.js"></script>
    <script type="text/javascript" src="/h-ui.admin/lib/respond.min.js"></script>
    <script type="text/javascript" src="/h-ui.admin/lib/PIE_IE678.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="/h-ui.admin/static/h-ui/css/H-ui.min.css" />
    <link rel="stylesheet" type="text/css" href="/h-ui.admin/static/h-ui.admin/css/H-ui.admin.css" />
    <link rel="stylesheet" type="text/css" href="/h-ui.admin/lib/Hui-iconfont/1.0.7/iconfont.css" />
    <link rel="stylesheet" type="text/css" href="/h-ui.admin/lib/icheck/icheck.css" />
    <link rel="stylesheet" type="text/css" href="/h-ui.admin/static/h-ui.admin/skin/default/skin.css" id="skin" />
    <link rel="stylesheet" type="text/css" href="/h-ui.admin/static/h-ui.admin/css/style.css" />
    <!--[if IE 6]>
    <script type="text/javascript" src="/js/DD_belatedPNG_0.0.8a-min.js" ></script>
    <script>DD_belatedPNG.fix('*');</script>
    <![endif]-->
    <title>微信公众平台管理系统</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
</head>
<body>
<header class="navbar-wrapper">
    <div class="navbar navbar-fixed-top">
        <div class="container-fluid cl">
            <span class="logo navbar-logo f-l mr-10 hidden-xs">微信公众平台管理系统</span>

            <nav id="Hui-userbar" class="nav navbar-nav navbar-userbar hidden-xs">
                <ul class="cl">
                    <li class="dropDown dropDown_hover"> <a href="#" class="dropDown_A"><?php echo $this->session->get('username');?> <i class="Hui-iconfont">&#xe6d5;</i></a>
                        <ul class="dropDown-menu menu radius box-shadow">
                            <li><a href="javascript:void(0);" id="btn-logout">退出</a></li>
                        </ul>
                    </li>
                    <li id="Hui-skin" class="dropDown right dropDown_hover"> <a href="javascript:;" class="dropDown_A" title="换肤"><i class="Hui-iconfont" style="font-size:18px">&#xe62a;</i></a>
                        <ul class="dropDown-menu menu radius box-shadow">
                            <li><a href="javascript:;" data-val="default" title="黑色">黑色</a></li>
                            <li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
                            <li><a href="javascript:;" data-val="green" title="绿色">绿色</a></li>
                            <li><a href="javascript:;" data-val="red" title="红色">红色</a></li>
                            <li><a href="javascript:;" data-val="yellow" title="黄色">黄色</a></li>
                            <li><a href="javascript:;" data-val="orange" title="绿色">橙色</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<aside class="Hui-aside">
    <input runat="server" id="divScrollValue" type="hidden" value="" />
    <div class="menu_dropdown bk_2">
        <ul>
            <li <?php echo $nav == 'index' ? 'class="current"' : '';?>><a href="/" data-title="首页" href="javascript:void(0)"><i class="Hui-iconfont">&#xe625;</i> 首页</a></li>
            <li <?php echo $nav == 'user_list' ? 'class="current"' : '';?>><a href="/user/list" data-title="用户" href="javascript:void(0)"><i class="Hui-iconfont">&#xe62d;</i> 用户</a></li>
            <li <?php echo $nav == 'group_list' ? 'class="current"' : '';?>><a href="/user/group/list" data-title="用户组" href="javascript:void(0)"><i class="Hui-iconfont">&#xe62b;</i> 用户组</a></li>
            <li <?php echo $nav == 'group_broadcast' ? 'class="current"' : '';?>><a href="/broadcast/group/list" data-title="群发消息" href="javascript:;"><i class="Hui-iconfont">&#xe6c5;</i> 群发消息</a></li>
        </ul>
    </div>
</aside>
<div class="dislpayArrow hidden-xs"><a class="pngfix" href="javascript:void(0);" onClick="displaynavbar(this)"></a></div>
<section class="Hui-article-box">
    <div id="Hui-tabNav" class="Hui-tabNav hidden-xs">
        <div class="Hui-tabNav-wp">
            <ul id="min_title_list" class="acrossTab cl">
                <?php if (isset($navtitle)) { ?>
                <li class="active"><span title="<?php echo $navtitle;?>" data-href=""><?php echo $navtitle;?></span><em></em></li>
                <?php } ?>
            </ul>
        </div>
        <div class="Hui-tabNav-more btn-group"><a id="js-tabNav-prev" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d4;</i></a><a id="js-tabNav-next" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d7;</i></a></div>
    </div>
    <div id="iframe_box" class="Hui-article">
        <div class="show_iframe">
            <div style="display:none" class="loading"></div>
            <!-- 主要内容 -->
            <?php echo $this->getContent();?>
        </div>
    </div>
</section>
<script type="text/javascript" src="/h-ui.admin/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/h-ui.admin/lib/layer/2.1/layer.js"></script>
<script type="text/javascript" src="/h-ui.admin/static/h-ui/js/H-ui.js"></script>
<script type="text/javascript" src="/h-ui.admin/static/h-ui.admin/js/H-ui.admin.js"></script>
<script type="text/javascript">
    $(function() {
        $("#btn-logout").click(function () {
            layer.confirm('您确定要退出吗？', {
                btn: ['是','否']
            }, function(){
                window.location.href = "/logout";
            }, function(){
                layer.close();
            });
        });
    });
</script>
</body>
</html>